/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as HomeImport } from "./routes/_home";
import { Route as HomeIndexImport } from "./routes/_home/index";

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: "/_home",
  getParentRoute: () => rootRoute,
} as any);

const HomeIndexRoute = HomeIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_home": {
      id: "/_home";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof HomeImport;
      parentRoute: typeof rootRoute;
    };
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexImport;
      parentRoute: typeof HomeImport;
    };
  }
}

// Create and export the route tree

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute;
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
};

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren);

export interface FileRoutesByFullPath {
  "": typeof HomeRouteWithChildren;
  "/": typeof HomeIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof HomeIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_home": typeof HomeRouteWithChildren;
  "/_home/": typeof HomeIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/";
  id: "__root__" | "/_home" | "/_home/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_home"
      ]
    },
    "/_home": {
      "filePath": "_home.tsx",
      "children": [
        "/_home/"
      ]
    },
    "/_home/": {
      "filePath": "_home/index.tsx",
      "parent": "/_home"
    }
  }
}
ROUTE_MANIFEST_END */
